/*
    Squeak.h
    Generated by FMOD Designer v4.32.8 
*/

#ifndef SQUEAK_H
#define SQUEAK_H

/*
    Total number of events in the project
*/
const int EVENTCOUNT_SQUEAK = 1;

/*
    EventGroup/Event-relative indices
*/
const int EVENTGROUP_SQUEAK_FINGERDRAGGROUP = 0;
const int EVENTGROUPCOUNT_SQUEAK_FINGERDRAGGROUP = 1;
const int EVENT_SQUEAK_FINGERDRAGGROUP_FINGERDRAG = 0;
const int EVENTPARAMETER_SQUEAK_FINGERDRAGGROUP_FINGERDRAG_FINGERSPEED = 0;

/*
    Project-unique event ids
*/
const int EVENTID_SQUEAK_FINGERDRAGGROUP_FINGERDRAG = 0;

const int EVENTCATEGORY_SQUEAK_MASTER = 0;
const int EVENTCATEGORYCOUNT_SQUEAK_MASTER = 1;

const int EVENTCATEGORY_SQUEAK_MASTER_MUSIC = 0;
const int EVENTCATEGORYCOUNT_SQUEAK_MASTER_MUSIC = 0;


/*
    Event GUIDs
*/
const char *EVENTGUID_SQUEAK_FINGERDRAGGROUP_FINGERDRAG = "{e833b04b-34fd-45f9-84cb-562080522b0e}";

#endif /* SQUEAK_H */
